# -*- coding: utf-8 -*-
"""marca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtbsJf7ufBe7kpJxHgKPLC-GeF1urT6_

# Adicionar marca d'água em uma imagem

# Imports
"""

from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

"""# Abrir imagem"""

image = Image.open("top.jpg")
image.show()
plt.imshow(image)

size = (500, 100)
crop_image = image.copy()
crop_image.thumbnail(size)

"""# Imagem que será a marca d'água"""

marca = Image.open("logo.png")
marca.show()
plt.imshow(marca)

"""# Marca d'água inserida na imagem escolhida"""

copied_image = image.copy()
copied_image.paste(marca, (1780, 1050))
plt.imshow(copied_image)